### DISCUSSION TITLE
How to deploy Bangle-io using docker?

### DISCUSSION THREAD

**Discussion by cinetube** [bangle-io/bangle-io#216] [Q&A] [answered]
How to deploy Bangle-io using docker?

**Comment by BearDooks** [comment, marked as answer]
@cinetube looks like there is no docker image for this. That being said I am also curious since I would love to test it on my server and then blow it away after I break it 😄 

I am going to see if I can write my own simple dockerfile to handle this. If I get it working I am more than willing to share with you and everyone else

**Reply by BearDooks** [reply]
@cinetube and @kepta 

Here is what I wrote (I am no expert by any means, but it seems to be working for now)

> **dockerfile**

```
FROM alpine:latest

# Environment Variables
ENV HTTPS_GIT_REPO "https://github.com/bangle-io/bangle-io.git"

# Updates and installs to the server
RUN apk update
RUN apk add --no-cache bash
RUN apk add --no-cache wget
RUN apk add --no-cache yarn
RUN apk add --no-cache git

# Make directory needed for app
RUN mkdir /bangle-dev

# Download the repo via git
WORKDIR /bangle-dev
RUN git clone ${HTTPS_GIT_REPO} .

# Build the app
RUN yarn install

# Run the app (will be in background)
# --host allows to run on network
# & at the end runs in background
RUN yarn start --host&
```


> **docker-compose.yml**

```
version: '3'

services:
  bangle-dev:
    build: .
    ports:
      - "4000:4000"
    tty: true
    container_name: bangle-dev
```

and I was able to start it with `docker-compose up -d`

Hope this helps both of you!

**Reply by kepta** [reply]
For production cases, I would recommend using `yarn build` and using a static server to serve the static files.  I have created a similar script for building and serving by running `yarn g:build-prod-serve`.

**Reply by BearDooks** [reply]
I have never really used yarn before, so good to know. Thanks!

**Comment by WGandy** [comment]
I tried the Dockerfile and compose files and it builds and runs without error but I'm not able to connect to it. stdout just says 

`Attaching to bangle-dev`

This test is running in a VPS so I may have some kind of dns or connection issue. I'll try it again on a local server soon.

**Comment by boppy** [comment]
As I also had this question, I created a reduced Dockerfile to create the container. tl;dr first:

<details>
<summary><code>Dockerfile</code></summary>

```Dockerfile
FROM alpine:latest

RUN apk add --no-cache yarn git \
    && git clone --depth 1 --branch dev https://github.com/bangle-io/bangle-io.git app

WORKDIR /app
ENV NODE_ENV=production
RUN yarn install && yarn vite build
RUN rm -rf .git

CMD yarn e2e-serve
```

</details>

<details>
<summary><code>docker-compose.yaml</code></summary>

```yaml
version: "3.7"
services:
  bangle:
    build:
      context: ./
    environment:
      TZ: Europe/Berlin         # Be sure to change
    restart: unless-stopped
    ports:
      - "127.0.0.1:3402:1234"   # Also be sure to do whatever it needs on your system ;)
```

</details>

## Why does it differ so much from @BearDooks example?

It reduces the steps taken to build the image, doesn't install applications that are not used (`bash` and `wget`), only clones the latest data (`--depth 1`) from the `dev` branch (`--branch dev`) and therefore reduces the cloned size from 1.4 GB to 227 MB (still kinda huge, tbh)! It will then use the "built-in" `e2e-serve` to serve the app to port `1234`, as per [package.json](https://github.com/bangle-io/bangle-io/blob/dev/package.json#L30). It also stays in foreground, as most containers do and will not need the `tty` flag because of that.

## Is there a still an even better way?

Yes, there still is, but it doesn't use docker in _the usual way_. As the app is 100% browser-based, all the sources are not needed to run anyways, so it's enough to build the app once and serve it using a static file server, as nginx. This also missively reduces attack surface because no yarn-based application is run to serve static files.

I finally went that way and used this file set:

<details>
<summary><code>Dockerfile</code></summary>

This Dockerfile only clones the repo once, but makes a pull on each invocation of the container. So after every run of the container (it's one-shot, so it quits after it ran successfully), the git repo inside the container is up-to-date. `yarn install` and `yarn build` are executed after the pull. The `build` directory should be mounted to the container, so you can take to files to serve them from there.

```Dockerfile
FROM alpine:latest

RUN apk add --no-cache yarn git \
    && git clone --depth 1 --branch dev https://github.com/bangle-io/bangle-io.git app

COPY build.sh /build.sh
RUN chmod +x /build.sh

WORKDIR /app
ENV NODE_ENV=production
VOLUME /app/build

CMD /build.sh
```

</details>

<details>
<summary><code>build.sh</code></summary>

```shell
#!/bin/ash
# just to be sure: Change to /app directory
cd /app

# get latest data from git repo
git pull -q --rebase origin dev

# do the installation
yarn install

# do the build
yarn vite build

# confirm and quit
echo
echo "Build completed."

```

</details>

<details>
<summary><code>docker-compose.yaml</code></summary>

```yaml
version: "3.7"
services:
  bangle-build:
    build:
      context: ./
    environment:
      TZ: Europe/Berlin             # Be sure to change
    restart: "no"
    volumes:
      - /var/www/bangle:/app/build  # Might also need a change
```

</details>

<details>
<summary><code>nginx-bangle.conf</code></summary>

```nginx
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name bangle.example.com;

    include             params/ssl;
    ssl_certificate     certs/bangle.example.com/fullchain.cer;
    ssl_certificate_key certs/bangle.example.com/bangle.example.com.key;

    access_log          logs/example.com__bangle__access.log main;
    error_log           logs/example.com__bangle__error.log;

    location / {
        root /var/www/bangle;
        try_files $uri /index.html;
    }
}
```

</details>

Just to be sure: This only runs the container to build the static files. The container DOES NOT run all the time bangle is accessible! It's by design and should not make you worry! ;)

**Reply by ovizii** [reply]
Hopefully one day somebody will create a container image we can just pull to run bangle.io without having to build our own.

**Reply by BearDooks** [reply]
@boppy That's awesome! I am still learning a lot, so I really appreciate you explaining some of the things you did.

**Reply by Bramard** [reply]
> As I also had this question, I created a reduced Dockerfile to create the container. tl;dr first:
> 
> `Dockerfile`
> `docker-compose.yaml`
> ## Why does it differ so much from @BearDooks example?
> It reduces the steps taken to build the image, doesn't install applications that are not used (`bash` and `wget`), only clones the latest data (`--depth 1`) from the `dev` branch (`--branch dev`) and therefore reduces the cloned size from 1.4 GB to 227 MB (still kinda huge, tbh)! It will then use the "built-in" `e2e-serve` to serve the app to port `1234`, as per [package.json](https://github.com/bangle-io/bangle-io/blob/dev/package.json#L30). It also stays in foreground, as most containers do and will not need the `tty` flag because of that.
> 
> ## Is there a still an even better way?
> Yes, there still is, but it doesn't use docker in _the usual way_. As the app is 100% browser-based, all the sources are not needed to run anyways, so it's enough to build the app once and serve it using a static file server, as nginx. This also missively reduces attack surface because no yarn-based application is run to serve static files.
> 
> I finally went that way and used this file set:
> 
> `Dockerfile`
> `build.sh`
> `docker-compose.yaml`
> `nginx-bangle.conf`
> Just to be sure: This only runs the container to build the static files. The container DOES NOT run all the time bangle is accessible! It's by design and should not make you worry! ;)

That solution works great for me, thanks.

Here is how I'm running it :

* Dockerfile :

```
FROM alpine:latest

RUN apk add --no-cache yarn git \
    && git clone --depth 1 --branch main https://github.com/bangle-io/bangle-io.git app

COPY build.sh /build.sh
RUN chmod +x /build.sh

WORKDIR /app
ENV NODE_ENV=production
VOLUME /app/build

CMD /build.sh
```

* build.sh :

```
#!/bin/ash
# Change to /app directory
cd /app

# Get latest data from git repo
git pull -q --rebase origin main

# Install dependencies
yarn install

# Build the project
yarn vite build

# Confirm and quit
echo
echo "Build completed."
```

* docker-compose.yml :

```
services:
# This service is generating the bangle frontend static files. Run once then stop.
  bangle-build:
    build:
      context: ./
    environment:
      TZ: Europe/Berlin
    restart: "no"
    volumes:
      - bangle_build:/app/build

# The nginx service is used to serve the static files built previously.
# Log rotation is set up.
  nginx:
    image: nginx:latest
    container_name: nginx-bangle
    volumes:
      - bangle_build:/var/www/bangle:ro
      - ./nginx-bangle.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx-bangle-logrotate.conf:/etc/logrotate.d/nginx-bangle:ro
    ports:
      - "12345:80"
    restart: unless-stopped
    depends_on:
      - bangle-build

volumes:
  bangle_build:
```

* nginx-bangle.conf :

```
server {
        listen 80;
        server_name bangle.example.com;

        access_log /var/log/nginx/bangle_access.log;
        error_log /var/log/nginx/bangle_error.log;

        location / {
                root /var/www/bangle;
                index index.html;
                try_files $uri /index.html;
        }
}
```

* nginx-bangle-logrotate.conf :

```
/var/log/nginx/bangle_access.log
/var/log/nginx/bangle_error.log {
        weekly
        rotate 4
        missingok
        notifempty
        compress
        delaycompress
        sharedscripts
        postrotate
            [ -f /var/run/nginx.pid ] && kill -USR1 `cat /var/run/nginx.pid`
        endscript
}
```

This is a simple http setup that I use behind a different nginx instance that handles SSL stuff.

I had to set it up this way to make bangle-io work as a PWA app :

```
server {
        listen  80;
        server_name     bangle.example.com;

        # HTTP - redirect http requests to https
        location / {
                return 301 https://$host$request_uri;
        }
}

server {
        listen  443 ssl;

        server_name bangle.example.com;
        ssl_certificate /etc/letsencrypt/live/bangle.example.com/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/bangle.example.com/privkey.pem; # managed by Certbot

        ssl_protocols   TLSv1 TLSv1.1 TLSv1.2;

        location / {
                # add authentication
                include /etc/nginx/snippets/userlist;

                include proxy_params;
                proxy_pass http://<DOCKER_HOST_IP>:12345;
        }

        # Explicitly serve the manifest.webmanifest file with the correct MIME type (for PWA browser app correct detection)
        location = /manifest.webmanifest {
               # Exempt manifest from authentication
               auth_basic off;
			   
			   # MIME type
               add_header Content-Type application/manifest+json;
			   
			   include proxy_params;
               proxy_pass http://<DOCKER_HOST_IP>:12345/manifest.webmanifest;
        }
}
```
